### ISSUE TITLE
CSProj Error : ASP.NET Core

### ISSUE THREAD

**Issue by benyaminl** [coc-extensions/coc-omnisharp#27]
Hello, I got error for not having sln on the project, does this extension doesn't support .csproj file and ASP.NET? 
```log
[Error  - 15:05:51] Starting client failed 
  Message: Internal Error - System.ArgumentException: OmniSharp only supports being launched with a directory path or a path to a solution (.sln) file.

Parameter name: path

   at OmniSharp.Services.OmniSharpEnvironment..ctor(String path, Int32 hostPid, LogLevel logLevel, String[] additionalArguments) in D:\a\1\s\src\OmniSharp.Host\Services\OmniSharpEnvironment.cs:line 38

   at OmniSharp.LanguageServerProtocol.LanguageServerHost.CreateCompositionHost(InitializeParams initializeParams) in D:\a\1\s\src\OmniSharp.LanguageServerProtocol\LanguageServerHost.cs:line 84

   at OmniSharp.LanguageServerProtocol.LanguageServerHost.Initialize(ILanguageServer server, InitializeParams initializeParams) in D:\a\1\s\src\OmniSharp.LanguageServerProtocol\LanguageServerHost.cs:line 157

   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()

   at System.Threading.Tasks.Task.WhenAll(IEnumerable`1 tasks)

   at OmniSharp.Extensions.LanguageServer.Server.LanguageServer.<MediatR-IRequestHandler<OmniSharp-Extensions-LanguageServer-Protocol-Models-InitializeParams\,OmniSharp-Extensions-LanguageServer-Protocol-Models-InitializeResult>-Handle>d__55.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.<Handle>d__5.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MediatR.Pipeline.RequestPostProcessorBehavior`2.<Handle>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at MediatR.Pipeline.RequestPreProcessorBehavior`2.<Handle>d__2.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>d__6.MoveNext()
  Code: -32602 

```
Thank you

**Comment by yatli** [comment]
What's your `:pwd` ?

**Comment by yatli** [comment]
Also check `:CocInfo` to see workspace detection.

**Comment by benyaminl** [comment]
Okay. I did, it's on the root of dotnet core web project. 
```log
## versions

vim version: VIM - Vi IMproved 8.2 8021364
node version: v12.13.0
coc.nvim version: 0.0.78-0ff42027ff
coc.nvim directory: C:\Users\Ben\.vim\plugged\coc.nvim
term: undefined
platform: win32

## Output channel: coc-omnisharp

coc-omnisharp activated.
workspace root=webapp\

## Output channel: cs

```

See the folder 
![image](https://user-images.githubusercontent.com/2817332/89671107-9c19e880-d90c-11ea-9dfc-60a467a05a1c.png)

**Comment by benyaminl** [comment]
> 
> 
> Also check `:CocInfo` to see workspace detection.

Hello any update on this? I wanted to know why this happen. haha..

**Comment by yatli** [comment]
will be fixed in 0.27

**Comment by emiliano-ruiz** [comment]
As far as I'm concerned this was fixed in the [last commit](https://github.com/coc-extensions/coc-omnisharp/commit/eec9ba0de674850d3b6452d4d1c4cc9dd3d6bdcd).

At least in Manjaro (linux). Did not test in Windows.

**Comment by yatli** [comment]
Should be fixed. Closing now.
