### ISSUE TITLE
Error activating Plugins : Error Undefined read browser_download_url

### ISSUE THREAD

**Issue by benyaminl** [coc-extensions/coc-omnisharp#72]
```
ERROR (pid:3156) [extensions] - Error on active extension coc-omnisharp: Cannot read properties of undefined (reading 'browser_download_url') TypeError: Cannot read properties of undefined (reading 'browser_download_url')
    at LanguageServerProvider.<anonymous> (C:\Users\benli\AppData\Local\coc\extensions\node_modules\coc-omnisharp\node_modules\coc-utils\out\langserver.js:44:44)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\benli\AppData\Local\coc\extensions\node_modules\coc-omnisharp\node_modules\coc-utils\out\langserver.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by yatli** [comment]
Ow naw. it fails completely now.
I'd recommend `csharp-ls` instead of `omnisharp` at this point. Very predictable.

**Comment by yatli** [comment]
Emm, the latest version is 0.4.0
Not sure why nuget recommends 0.1.2 tho

**Comment by benyaminl** [comment]
> Emm, the latest version is 0.4.0 Not sure why nuget recommends 0.1.2 tho
> 
> Also, if you do `dotnet install --global csharp-ls` it will be available as a command line tool, no need to kick start with `dotnet xxx.dll --xxx --yyy`
> 
> Edit:
> 
> I know now. You must've followed my link in README which is stale and pointed to csharp-ls 0.1.2 lol. Corrected.

no it's the nuget that suggesting 0.1.2 I think, anyway seems still got error. 
```
{
    "languageserver": {
        "csharp-ls": {
          "command": "csharp-ls",
          "filetypes": ["cs"],
          "rootPatterns": ["*.csproj", ".vim/", ".git/", ".hg/"]
        }
    }
}
```

Take your time, I will also look into the lsp implementation myself to learn how it works. I really thankful for your work kindly sir.
